export const revenue = [
    { month: "January", revenue: 12000 },
    { month: "February", revenue: 15000 },
    { month: "March", revenue: 13500 },
    { month: "April", revenue: 16000 },
    { month: "May", revenue: 14500 },
    { month: "June", revenue: 17000 },
    { month: "July", revenue: 18000 },
    { month: "August", revenue: 15500 },
    { month: "September", revenue: 19000 },
    { month: "October", revenue: 20000 },
    { month: "November", revenue: 20000 },
    { month: "December", revenue: 20000 },
];

export const customers = [
    {
        id: 1,
        name: "John Doe",
        email: "john@example.com",
        joined: "2025-01-10",
        status: "Active",
        totalRevenue: 12000,
    },
    {
        id: 2,
        name: "Jane Smith",
        email: "jane@example.com",
        joined: "2025-01-15",
        status: "Active",
        totalRevenue: 10500,
    },
    {
        id: 3,
        name: "Michael Lee",
        email: "michael@example.com",
        joined: "2025-02-01",
        status: "Inactive",
        totalRevenue: 3800,
    },
    {
        id: 4,
        name: "Sarah Kim",
        email: "sarah@example.com",
        joined: "2025-02-05",
        status: "Active",
        totalRevenue: 9800,
    },
    {
        id: 5,
        name: "Chris Evans",
        email: "chris@example.com",
        joined: "2025-02-20",
        status: "Pending",
        totalRevenue: 4500,
    },
    {
        id: 6,
        name: "Lisa Brown",
        email: "lisa@example.com",
        joined: "2025-03-01",
        status: "Active",
        totalRevenue: 7200,
    },
    {
        id: 7,
        name: "Tom Hanks",
        email: "tom@example.com",
        joined: "2025-03-10",
        status: "Inactive",
        totalRevenue: 3100,
    },
    {
        id: 8,
        name: "Nina Hart",
        email: "nina@example.com",
        joined: "2025-03-15",
        status: "Active",
        totalRevenue: 8900,
    },
    {
        id: 9,
        name: "Daniel Wu",
        email: "daniel@example.com",
        joined: "2025-03-18",
        status: "Active",
        totalRevenue: 6700,
    },
    {
        id: 10,
        name: "Emma Stone",
        email: "emma@example.com",
        joined: "2025-03-20",
        status: "Pending",
        totalRevenue: 5000,
    },
];

export const reports = [
    {
        id: 1,
        title: "Q1 Sales Report",
        date: "2025-03-01",
        type: "Sales",
        status: "Completed",
    },
    {
        id: 2,
        title: "Customer Feedback",
        date: "2025-03-03",
        type: "Feedback",
        status: "Completed",
    },
    {
        id: 3,
        title: "Monthly Revenue",
        date: "2025-03-05",
        type: "Finance",
        status: "Pending",
    },
    {
        id: 4,
        title: "Automation Summary",
        date: "2025-03-07",
        type: "Automation",
        status: "Completed",
    },
    {
        id: 5,
        title: "Leads Overview",
        date: "2025-03-09",
        type: "Marketing",
        status: "Failed",
    },
    {
        id: 6,
        title: "Retention Analysis",
        date: "2025-03-10",
        type: "Customer",
        status: "Completed",
    },
    {
        id: 7,
        title: "Weekly Summary",
        date: "2025-03-12",
        type: "Summary",
        status: "Completed",
    },
    {
        id: 8,
        title: "Engagement Metrics",
        date: "2025-03-14",
        type: "Analytics",
        status: "Pending",
    },
    {
        id: 9,
        title: "Churn Rate Report",
        date: "2025-03-16",
        type: "Customer",
        status: "Completed",
    },
    {
        id: 10,
        title: "Revenue Forecast",
        date: "2025-03-18",
        type: "Finance",
        status: "Completed",
    },
];

export const automations = [
    {
        id: 1,
        name: "Welcome Email",
        trigger: "New Customer Signup",
        action: "Send Email",
        status: "Active",
    },
    {
        id: 2,
        name: "Lead Score Update",
        trigger: "Form Submission",
        action: "Update Lead Score",
        status: "Active",
    },
    {
        id: 3,
        name: "Follow-up Reminder",
        trigger: "No Interaction 7 Days",
        action: "Notify Sales Team",
        status: "Inactive",
    },
    {
        id: 4,
        name: "Invoice Generator",
        trigger: "Deal Won",
        action: "Create Invoice",
        status: "Active",
    },
    {
        id: 5,
        name: "Birthday Email",
        trigger: "Customer Birthday",
        action: "Send Email",
        status: "Pending",
    },
    {
        id: 6,
        name: "Churn Alert",
        trigger: "Inactivity 30 Days",
        action: "Send Alert",
        status: "Active",
    },
    {
        id: 7,
        name: "Feedback Request",
        trigger: "Purchase Completed",
        action: "Send Survey",
        status: "Active",
    },
    {
        id: 8,
        name: "Upsell Offer",
        trigger: "High Engagement",
        action: "Send Offer",
        status: "Inactive",
    },
    {
        id: 9,
        name: "Report Summary",
        trigger: "Every Monday",
        action: "Email Report",
        status: "Active",
    },
    {
        id: 10,
        name: "Trial Ending Reminder",
        trigger: "Trial Expiry 3 Days",
        action: "Send Reminder",
        status: "Pending",
    },
];

export const customersGrowth = [
    { month: "January", customers: 150 },
    { month: "February", customers: 100 },
    { month: "March", customers: 250 },
    { month: "April", customers: 200 },
    { month: "May", customers: 400 },
    { month: "June", customers: 350 },
    { month: "July", customers: 450 },
    { month: "August", customers: 300 },
    { month: "September", customers: 500 },
    { month: "October", customers: 550 },
    { month: "November", customers: 300 },
    { month: "December", customers: 600 },
];
